name: FRC I2C Mux

on:
  push:
    paths:
    - '**.kicad_sch'
    - '**.kicad_pcb'
  pull_request:
    paths:
      - '**.kicad_sch'
      - '**.kicad_pcb'

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@dev_k6
    - uses: INTI-CMNB/KiBot@v1_k6
      with:
      # Required - kibot config file
        config: configs/PCBWay.kibot.yaml
      # optional - prefix to output defined in config
        dir: output
      # optional - schematic file
        schema: '*.kicad_sch'
      # optional - PCB design file
        board: '*.kicad_pcb'
    - name: upload results
      uses: actions/upload-artifact@v2
      with:
        name: output
        path: output
